# Generated by Django 5.2.7 on 2025-11-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0003_parking_center_latitude_parking_center_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingentrance',
            name='address_line',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parkingentrance',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='parkings.parking'),
        ),
    ]
