# Generated by Django 5.2.7 on 2025-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_make_remove_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
