# Generated by Django 5.2.8 on 2025-11-24 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0008_alter_spot_zone'),
        ('vehicles', '0004_alter_parkingsession_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='parkings.parking'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
            preserve_default=False,
        ),
    ]
