# Generated by Django 5.2.8 on 2025-11-24 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_parkingsession_parking_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
