# Generated by Django 5.2.7 on 2026-02-07 15:11

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to=vehicles.models.fine_evidence_path),
        ),
        migrations.AddField(
            model_name='fine',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='grace_period_minutes',
            field=models.IntegerField(default=5),
        ),
    ]
