# Generated by Django 5.2.7 on 2026-02-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_fine_evidence_image_fine_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='contestation_reason',
            field=models.TextField(blank=True, help_text='Reason provided by user for disputing the fine', null=True),
        ),
    ]
