# Generated by Django 5.2.7 on 2026-02-07 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_fine_contestation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_violations', models.IntegerField(default=3, help_text='Maximum number of violations before user block/alert')),
                ('grace_period_minutes', models.IntegerField(default=15, help_text='Grace period (minutes) after parking expiration')),
            ],
            options={
                'verbose_name': 'Global System Configuration',
                'verbose_name_plural': 'Global System Configuration',
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Parking Violation', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_types', to='vehicles.globalsettings')),
            ],
        ),
    ]
