# Generated by Django 5.2.7 on 2026-02-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_globalsettings_violationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='grace_period_minutes',
            field=models.IntegerField(default=15, help_text='Minuti di tolleranza'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='max_violations',
            field=models.IntegerField(default=3, help_text='Violazioni max prima del ban'),
        ),
    ]
