# Generated by Django 5.2.7 on 2026-02-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_globalsettings_grace_period_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': 'System Configuration', 'verbose_name_plural': 'System Configuration'},
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='max_violations',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='max_violations_before_ban',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
