# Generated by Django 5.2.7 on 2026-02-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_globalsettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationtype',
            name='settings',
        ),
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
        migrations.DeleteModel(
            name='ViolationType',
        ),
    ]
