# Generated by Django 5.2.7 on 2026-02-07 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_remove_violationtype_settings_delete_globalsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_violations', models.IntegerField(default=3, help_text='Violazioni max prima del ban')),
                ('grace_period_minutes', models.IntegerField(default=15, help_text='Minuti di tolleranza')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Parking Violation', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_types', to='vehicles.globalsettings')),
            ],
        ),
    ]
