# Generated by Django 5.2.7 on 2026-02-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_globalsettings_violationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='tariff_1_name',
            field=models.CharField(default='Divieto di Sosta', max_length=100),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tariff_1_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tariff_2_name',
            field=models.CharField(default='Parcheggio Scaduto', max_length=100),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tariff_2_price',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tariff_3_name',
            field=models.CharField(default='Zona Rimozione', max_length=100),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tariff_3_price',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='grace_period_minutes',
            field=models.IntegerField(default=15, help_text='Tolleranza'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='max_violations',
            field=models.IntegerField(default=3, help_text='Soglia Ban'),
        ),
        migrations.DeleteModel(
            name='ViolationType',
        ),
    ]
