# Generated by Django 5.2.7 on 2026-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_globalsettings_tariff_1_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='tariff_1_name',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='tariff_1_price',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='tariff_2_name',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='tariff_2_price',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='tariff_3_name',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='tariff_3_price',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='violation_config',
            field=models.JSONField(blank=True, default=list, help_text='Inserisci le tariffe in formato JSON. Es: [{"name": "Divieto", "amount": 50}, {"name": "Scaduto", "amount": 30}]'),
        ),
    ]
