# Generated by Django 5.2.8 on 2026-01-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_cities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
