runtime: python314

env: standard

entrypoint: gunicorn -b :$PORT tps_backend.wsgi:application

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

env_variables:
  DJANGO_SETTINGS_MODULE: 'tps_backend.settings'
  DEBUG: 'False'

handlers:
- url: /static
  static_dir: staticfiles/
  
- url: /.*
  script: auto