# Generated by Django 5.2.7 on 2025-11-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='parking',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='parking',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spot',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='spot',
            name='zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
