# Generated by Django 5.2.7 on 2025-11-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_parking_rate_per_hour_alter_parking_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ParkingEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(help_text="Indirizzo stradale dell'ingresso", max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('parking', models.ForeignKey(help_text='Parcheggio a cui appartiene questo ingresso', on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='parkings.parking')),
            ],
        ),
    ]
