# Generated by Django 5.2.7 on 2025-11-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0004_alter_parkingentrance_address_line_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='center_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='center_longitude',
            new_name='longitude',
        ),
    ]
