# Generated by Django 5.2.7 on 2025-11-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0005_rename_center_latitude_parking_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='tariff_config_json',
            field=models.TextField(default='{\n    "type": "HOURLY_LINEAR",\n    "daily_rate": 20.00,\n    "day_base_rate": 2.50,\n    "night_base_rate": 1.50,\n    "night_start_time": "22:00",\n    "night_end_time": "06:00",\n    "flex_rules": []\n}'),
        ),
    ]
