# Generated by Django 5.2.7 on 2025-11-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0006_parking_tariff_config_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='floor',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='spot',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='spot',
            name='zone',
            field=models.CharField(blank=True, default='A', max_length=20),
        ),
    ]
