# Generated by Django 5.2.7 on 2025-11-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0007_alter_spot_floor_alter_spot_number_alter_spot_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
