# Generated by Django 5.2.7 on 2026-02-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0009_add_polygon_coordinates'),
    ]

    operations = [
    ]
