# Generated by Django 5.2.7 on 2026-02-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0011_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
