# Generated by Django 5.2.7 on 2026-02-04 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0012_city_center_latitude_city_center_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.CreateModel(
            name='ManagerCityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_managers', to='parkings.city')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager City Permission',
                'verbose_name_plural': 'Manager City Permissions',
                'unique_together': {('manager', 'city')},
            },
        ),
    ]
