# Generated by Django 5.2.8 on 2026-02-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0013_alter_city_options_managercitypermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerCityPermission',
        ),
    ]
