"""
Django settings for tps_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from django.templatetags.static import static
from django.urls import reverse_lazy
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-0ipfdb^onls00@#b_lu-b%zyvlhv)3aj)1*m@fko^=#iwm7uk^'
SECRET_KEY = os.environ["SECRET_KEY"]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# ALLOWED_HOSTS = ['127.0.0.1', '10.0.2.2', 'localhost', '0.0.0.0']

# Deployment settings
ALLOWED_HOSTS = [
    '127.0.0.1', 
    '10.0.2.2',
    'localhost',
    '0.0.0.0',
    '.appspot.com',
    'tps-parking-system.appspot.com',
    '*',
]
# Application definition

INSTALLED_APPS = [
    "unfold",  # Must be before django.contrib.admin
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # Your apps
    'users',
    'parkings',  
    'vehicles',
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Deployment requirement
    'whitenoise.middleware.WhiteNoiseMiddleware',
    #
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'tps_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tps_backend.wsgi.application'

# Database configuration
# Please choose one of the following configurations:

# ===== Neon Cloud Database  https://neon.com/ =====
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'neondb',
        'USER': 'neondb_owner',
        'PASSWORD': 'npg_1eQzFi3XoMJG',
        'HOST': 'ep-empty-sea-agiftapm-pooler.c-2.eu-central-1.aws.neon.tech',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# ===== Local PostgreSQL Database =====
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'tps_db',
#         'USER': 'postgres',
#         'PASSWORD': 'Aa314159',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


AUTH_PASSWORD_VALIDATORS = []

MEDIA_URL = '/media/'


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True




STATIC_URL = 'static/'



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

AUTH_USER_MODEL = 'users.CustomUser'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": None,  # Remove title from sidebar
    "SITE_HEADER": "TPS Admin Panel",
    "DASHBOARD_CALLBACK": "tps_backend.dashboard.dashboard_callback",
    "SITE_URL": "/",
    "SITE_ICON": None,
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "User Management",
                "collapsible": True,
                "items": [
                    {
                        "title": "Admins",
                        "icon": "admin_panel_settings",
                        "link": lambda request: "/admin/users/customuser/?role__exact=superuser",
                    },
                    {
                        "title": "Managers",
                        "icon": "supervisor_account",
                        "link": lambda request: "/admin/users/customuser/?role__exact=manager",
                    },
                    {
                        "title": "Patrollers", 
                        "icon": "local_police",
                        "link": lambda request: "/admin/users/customuser/?role__exact=controller",
                    },
                    {
                        "title": "All Users",
                        "icon": "group",
                        "link": lambda request: "/admin/users/customuser/",
                    },
                    {
                        "title": "Vehicles",
                        "icon": "directions_car",
                        "link": lambda request: "/admin/vehicles/vehicle/",
                    },
                    {
                        "title": "Patroller Shifts",
                        "icon": "schedule",
                        "link": lambda request: "/admin/users/shift/",
                    },
                ],
            },
            {
                "title": "Infrastructure",
                "collapsible": True,
                "items": [
                    {
                        "title": "Cities",
                        "icon": "location_city",
                        "link": lambda request: "/admin/parkings/city/",
                    },
                    {
                        "title": "Parkings",
                        "icon": "local_parking",
                        "link": lambda request: "/admin/parkings/parking/",
                    },
                    {
                        "title": "Entrances",
                        "icon": "meeting_room", 
                        "link": lambda request: "/admin/parkings/parkingentrance/",
                    },
                    {
                        "title": "Spots",
                        "icon": "grid_on",
                        "link": lambda request: "/admin/parkings/spot/",
                    },
                ],
            },
            {
                "title": "Sessions",
                "collapsible": True,
                "items": [
                    {
                        "title": "Parking Sessions",
                        "icon": "timer",
                        "link": lambda request: "/admin/vehicles/parkingsession/",
                    },
                    {
                        "title": "Violations", 
                        "icon": "gavel",
                        "link": lambda request: "/admin/vehicles/fine/",
                    },
                ],
            },
        ],
    },

    
    "STYLES": [
        lambda request: "/static/css/custom_admin.css",
    ],
    
    "SCRIPTS": [
        lambda request: "/static/js/custom_admin.js",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=60),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "ROTATE_REFRESH_TOKENS": True,
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST_USER = 'test@example.com' 
DEFAULT_FROM_EMAIL = 'TPS Support <test@example.com>'